export const ASSETS = {
  road: [
    "roadCorner.glb",
    "roadCornerCurved.glb",
    "roadCrossing.glb",
    "roadJunction.glb",
    "roadStraight.glb",
    "roadtSpli.glb",
  ],
  buildings: [
    "Big Building.glb",
    "Brown Building.glb",
    "Building Green corner fireExit.glb",
    "Building Green corner.glb",
    "Building Green fireExit.glb",
    "Building Green.glb",
    "Building Red Corner fireExit.glb",
    "Building Red Corner.glb",
    "Building Red fireExit.glb",
    "Building Red.glb",
    "Greenhouse.glb",
    "modern house model.glb",
  ],
  vehicles: [
    "Bicycle.glb",
    "Bus Stop.glb",
    "Bus stop sign.glb",
    "Bus.glb",
    "Car-unqqkULtRU.glb",
    "Car.glb",
    "Motorcycle.glb",
    "Pickup Truck.glb",
    "Planter & Bushes.glb",
    "Police Car.glb",
    "SUV.glb",
    "Sports Car-Gzj704DXdr.glb",
    "Sports Car.glb",
    "Van.glb",
  ],
  props: [
    "ATM.glb",
    "Adventurer.glb",
    "Air conditioner.glb",
    "Bench.glb",
    "Billboard.glb",
    "Box.glb",
    "Cone.glb",
    "Debris Papers.glb",
    "Dumpster.glb",
    "Fence End.glb",
    "Fence Piece.glb",
    "Fence.glb",
    "Fire Exit.glb",
    "Fire hydrant.glb",
    "Floor Hole.glb",
    "Flower Pot-Kgt363WkKd.glb",
    "Flower Pot.glb",
    "Mailbox.glb",
    "Manhole Cover.glb",
    "Power Box.glb",
    "Rock band poster.glb",
    "Roof Exit.glb",
    "Stop sign.glb",
    "Traffic Light.glb",
    "Trash Can.glb",
    "Tree.glb",
    "Washing Line.glb",
    "Yellow Post-it.glb",
    "airplane 3d model.glb",
    "coffre au tresor 3d.glb",
    "european_dragon.glb",
    "historical vehicles 3d model.glb",
    "medieval castle 3d model.glb",
    "modèle 3d d'aéroport.glb",
    "squelette guerrier 3d.glb",
    "titanic 3d model.glb",
    "trah bag grey.glb",
  ],
  people: [
    "Animated Woman-nIItLV9nxS.glb",
    "Animated Woman-qJ2gsTUBHL.glb",
    "Animated Woman.glb",
    "Man.glb",
    "woman.glb",
  ],
};

export function getURL(str) {
  return `../City Pack.undefined-glb/${str}`;
}
